### ISSUE TITLE
Etat développement

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/rmtr#1]
@fjacon, @fvanderbiest  Merci de me dire où en sont les spécifications de ce module et quand nous pourrons les consulter .
Je vous rappelle que nous avons fait un gros travail de montage des données sur notre PF de test et qu'il nous reste des questions en suspens .

**Comment by fjacon** [comment]
Les spécifications ne sont pas dans un état suffisamment avancé pour une relecture.
Nous travaillons cette semaine à la résolution des tickets Atlas.

**Comment by catmorales** [comment]
OK Merci
