### ISSUE TITLE
Mauvaise adresse e-mail paramétrée sur le module rmtr

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/rmtr#12]
Nous avons des messages d'erreurs sur notre support pour des demandes du module RMTR  qui n'aboutissent pas avec  l'adresse **portail@sig.rennesmetropole.fr** (pas connue de notre serveur de messagerie Microsoft Exchange...)
Il doit y avoir un mauvais paramétrage côté envoi de mails , l'adresse à utiliser est **portail.sig@rennesmetropole.fr**

**Comment by MaelREBOUX** [comment]
Le destinataire des mails doit être **s.gelin@rennesmetropole.fr**

**Comment by MaelREBOUX** [comment]
je viens de tester : il y a une erreur lors de l'envoi du mail.

**Comment by MaelREBOUX** [comment]
je reprécise :

subject : [RMTR] demande d'extraction
to: s.gelin@rennesmetropole.fr
cc: [le demandeur]

**Comment by MaelREBOUX** [comment]
Corrigé avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/986804c5fe0a3ea5a02e5ca35082a62c3917e9f2

A redéployer en test.

**Comment by Vampouille** [comment]
Je viens de déployer ça sur le serveur de test.

**Comment by catmorales** [comment]
je ferme car doublon
