### ISSUE TITLE
Erreur 403 sur envoi du mail

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/rmtr#13]
Failed to load resource: the server responded with a status of 403 (Forbidden)
POST https://portail-test.sig.rennesmetropole.fr/ldapadmin/emailProxy

![screenshot424](https://cloud.githubusercontent.com/assets/6370443/21386003/0caef40c-c771-11e6-95cc-d64c6e9b4cf7.png)

**Comment by MaelREBOUX** [comment]
on va voir si c'est lié à #12

**Comment by Vampouille** [comment]
Pour des raisons de sécurité, l'accès au proxy email est limité au rôle `ROLE_MOD_EMAILPROXY` :
https://github.com/georchestra/datadir/blob/master/security-proxy/security-mappings.xml#L21

@MaelREBOUX Il faudrait soit : 
* créer ce rôle et l'ajouter aux utilisateurs voulus
* changer ce rôle dans `security-mappings.xml` afin d'utiliser un autre rôle déjà existant

**Comment by MaelREBOUX** [comment]
N'importe quel utilisateur est susceptible de faire une commande d'extraction de ces données.

**Comment by Vampouille** [comment]
Je met le rôle `IS_AUTHENTICATED_FULLY` dans ce cas.

**Comment by Vampouille** [comment]
https://github.com/camptocamp/georchestra-rennes-configuration/commit/ffc698794627817c9314ef226028da63319204a5
C'est installé sur le serveur de test.

**Comment by MaelREBOUX** [comment]
nope : marche pas.

**Comment by MaelREBOUX** [comment]
Avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/986804c5fe0a3ea5a02e5ca35082a62c3917e9f2 j'ai enlevé le BCC. Ca a qqch à voir ?

**Comment by fvanderbiest** [comment]
Je viens de retester.
Cette fois c'est une erreur 500 : Recipient not allowed : portail.sig@rennesmetropole.fr

Et en effet, la configuration n'autorise pas cette adresse email: https://github.com/camptocamp/georchestra-rennes-configuration/blob/test/ldapadmin/ldapadmin.properties#L61 indique actuellement
```
emailProxyRecipientWhitelist=portail@sig.rennesmetropole.fr, sig@rennesmetropole.fr, s.gelin@rennesmetropole.fr
```

Il vous faut donc soit changer la config cliente ou la config serveur en conséquence.
Je laisse @catmorales opérer ici.

**Comment by catmorales** [comment]
c'est fait avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/5e1aa00cd594dc2bb11da56774e2123d6f3a3faf sur la branche de test, côté serveur , je vais redéployer ce soir le datadir donc ça devrait être bon ensuite.

**Comment by catmorales** [comment]
fait à retester @MaelREBOUX

**Comment by MaelREBOUX** [comment]
HTTP 200 et on reçoit immédiatement un mail

Par contre : l'adresse mail d'expédition c'est n'importe quoi !
C'est dynamique ? Si non mettre ```Portail SIG<portail.sig@rennesmetropole.fr```

![screenshot465](https://cloud.githubusercontent.com/assets/6370443/21926727/4f86bef8-d983-11e6-95cc-a5a7d4047b3b.png)

**Comment by catmorales** [comment]
fait dans https://github.com/camptocamp/georchestra-rennes-configuration/commit/e7503b6914ea1281047dd1c0d74ee46667281c87
à re-tester

**Comment by catmorales** [comment]
et déployé sur test ce jour

**Comment by catmorales** [comment]
redémarrage tomcat à l'instant et renvoi de mail . Pour moi, c'est bon.
