### ISSUE TITLE
Fermeture de la fenêtre après envoi du mail

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/rmtr#14]
Après envoi du mail de demande, la fenêtre ne se ferme pas.
Du coup : c'est tentant de recliquer sur le bouton "Envoi" car y'a pas de bouton "Fermer".

Donc, au choix à discuter :
- rajouter un bouton "Fermer"
- fermer la fenêtre sur HTTP200 de la requête proxymail

perso : je vote pour le bouton Fermer. @catmorales  ?

**Comment by catmorales** [comment]
Moi aussi à priori, je préfère le bouton "fermer".

**Comment by MaelREBOUX** [comment]
Vendu !

@fvanderbiest : à toi de jouer.

**Comment by catmorales** [comment]
suite à la discussion de ce jour on est donc OK pour une fermeture automatique  de la fenêtre après envoi du mail .

**Comment by fvanderbiest** [comment]
Fait avec 7b9df29

**Comment by catmorales** [comment]
addon à redéployer

**Comment by catmorales** [comment]
Déployé et testé ce jour . C'est bon !
