### ISSUE TITLE
Formulaire de saisie pour envoi de mail - 

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/rmtr#15]
* Nom de la collectivité Rennes_M_tropole à corriger
* Ne pas mettre null par défaut dans le champ téléphone
![image](https://cloud.githubusercontent.com/assets/4659829/21992433/b7593098-dc16-11e6-9d8a-e98b52487a18.png)

**Comment by fvanderbiest** [comment]
Le problème vient de là https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/filtered-resources/WEB-INF/jsp/index.jsp#L223

**Comment by fvanderbiest** [comment]
Pour la typo dans le nom de la collectivité, c'est côté security-proxy que ça se passe, car dans l'appli JS j'ai:
```
GEOR.config.USERORG = "<%=request.getHeader("sec-org") %>" = "Rennes_M_tropole"
```
Il s'agit de corriger l'issue https://github.com/georchestra/datadir/issues/40 en plus du problème d'encoding.

**Comment by fvanderbiest** [comment]
> Ne pas mettre null par défaut dans le champ téléphone

Corrigé sur master avec https://github.com/georchestra/georchestra/commit/ac4c51658288e0f45c6e2ad26375108e37d5d21e (à redéployer)

**Comment by Vampouille** [comment]
PR pour récupérer le nom lisible d'une organisation : https://github.com/georchestra/georchestra/pull/1667

*  [x] à merger dans ce dépot :
PR sur le datadir : https://github.com/georchestra/datadir/pull/51

**Comment by fvanderbiest** [comment]
PR ci-dessus mergées, datadir de test de RM mis à jour avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/c8fcf2e1dee468761f1d309edf8c9c9f53c34f38
Cela devrait donc être bon.

Dans l'ordre:
 * mettre à jour le datadir de la machine test
 * redéployer le security-proxy & mapfishapp

Le bug devrait être corrigé.

Par la suite, merger en cascade test -> prod -> extranet, mettre à jour le datadir sur les machines, puis redéployer le security-proxy & mapfishapp.

**Comment by catmorales** [comment]
Gros problème lors du déploiement du SP voir le ticket référencé ci-dessus.

**Comment by catmorales** [comment]
La valeur null n'apparait en effet plus dans le formulaire et le problème d'accent est également corrigé.
![image](https://cloud.githubusercontent.com/assets/4659829/23222753/31660378-f929-11e6-81fd-cc55fd265147.png)

**Comment by catmorales** [comment]
je ne ferme pas ce ticket car il reste à faire les merge sur les PF de prod . Cet addon est pour le moment désactivé en prod.

**Comment by catmorales** [comment]
Il est déployé en prod mais désactivé pour le moment, nous l'activerons le moment venu. Je ferme le ticket.
