### ISSUE TITLE
mail - rajouter \n pour renvoi à la ligne de la liste des tuiles

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/rmtr#16]
```
Les tuiles concernées sont les suivantes: 999-48-00193-01444-16-B-21, 999-48-00193-01444-16-B-16, 999-48-00193-01444-16-B-06
```

devient

```
Les tuiles concernées sont les suivantes: 
999-48-00193-01444-16-B-21, 999-48-00193-01444-16-B-16, 999-48-00193-01444-16-B-06
```

**Comment by catmorales** [comment]
fait dans notre profil de configuration https://github.com/camptocamp/georchestra-rennes-configuration/commit/2369721677e1764edc9aad083d93b2be89298774

**Comment by catmorales** [comment]
c'est bon:
![image](https://cloud.githubusercontent.com/assets/4659829/23222980/f70137c4-f929-11e6-9b96-6954b4187704.png)
