### ISSUE TITLE
[Mail] ajouter le nombre de dalles concernées dans le mail 

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/rmtr#17]
tout est dans le titre

**Comment by catmorales** [comment]
@fvanderbiest , relance sur ce point merci , ça simplifiera la gestion de notre côté pour la chaîne de traitement qui suit. Vu avec Frédéric.

**Comment by fvanderbiest** [comment]
Avec le commit ci-dessus, le sujet du mail devient aussi un template, comme le contenu du mail.
Par ailleurs la variable `count` contient le nombre de tuiles commandées, vous pouvez l'utiliser dans vos templates.

**Comment by fvanderbiest** [comment]
config et machine test à jours.
