### ISSUE TITLE
[Sélection dalles ] Limiter le nombre de dalles

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/rmtr#18]
Lors de la sélection des dalles, il est souhaitable de limiter cette sélection à 50 dalles et empêcher la sélection si la couche des dalles n'est pas affichée (plage d'échelle de visualisation notamment)

**Comment by catmorales** [comment]
Evolution à faire sur heures de support

**Comment by catmorales** [comment]
relance

**Comment by fvanderbiest** [comment]
Je regarde ça.

**Comment by fvanderbiest** [comment]
Fait avec 74b3f04 & config branche test mise à jour avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/b757919ddb72578ab61de6f1bd0efa24ef75d91f & déployé sur test.

**Comment by catmorales** [comment]
En testant ce matin, j'ai rencontré le problème suivant, en faisant une sélection linéaire:
![image](https://user-images.githubusercontent.com/4659829/27428468-68b8071e-5742-11e7-8932-3bcd0299e5c9.png)

**Comment by fvanderbiest** [comment]
C'est indépendant.

Problème lié à la donnée couche carroyage sous-jacente, ou à la forme dessinée.

**Comment by catmorales** [comment]
OK donc c'est bon
