### ISSUE TITLE
Modifier style de la couche rctr_carroyage

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/rmtr#2]
Mettre visu seulement à partir du 1/34 ou 1/17 0000

**Comment by MaelREBOUX** [comment]
grossir épaisseur des traits.

Laisser ce ticket ouvert car, dès que les données le permettent :
- fraîcheur des données
- contient ou pas des données topo

**Comment by catmorales** [comment]
@MaelREBOUX on peut fermer ?
Mais sur la PF de test c'est différent de la prod . pourquoi ?

**Comment by MaelREBOUX** [comment]
Fait
