### ISSUE TITLE
[Fenêtre résultat] Mettre la date de mise à jour au format français

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/rmtr#20]
![image](https://user-images.githubusercontent.com/4659829/27289750-576a9fb4-550b-11e7-90b4-be912b724cca.png)

**Comment by catmorales** [comment]
Format en base:  date_der_maj date DEFAULT '1970-01-01'::date,

**Comment by catmorales** [comment]
Changer le paramètre local dans le tomcat-georchestra résoudra sans doute le problème cf https://github.com/camptocamp/georchestra-rennes-configuration/issues/570

**Comment by fvanderbiest** [comment]
> Changer le paramètre local dans le tomcat-georchestra résoudra sans doute le problème

Non, le formatage est fait côté client.

**Comment by fvanderbiest** [comment]
Il suffit de changer le type date en string sur https://github.com/camptocamp/georchestra-rennes-configuration/blob/test/mapfishapp/addons/rmtr/config.json#L22

**Comment by catmorales** [comment]
OK je vais donc faire cette correction sur notre configuration de test ainsi que #19

**Comment by catmorales** [comment]
https://github.com/camptocamp/georchestra-rennes-configuration/blob/test/mapfishapp/addons/rmtr/config.json#L22

**Comment by catmorales** [comment]
OK c'est mieux . Merci
![image](https://user-images.githubusercontent.com/4659829/27339659-a36ddc5a-55d8-11e7-973a-80569a55d3d7.png)
