### ISSUE TITLE
Rajouter affichage attribut date_der_maj

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/rmtr#3]
@fvanderbiest un truc passé sous les radars sauf qu'on en parle depuis 2 ans... Donc c'est le moment de le faire.

Nous venons de rajouter un attribut **date_der_maj**  sur la couche.
Merci de le rajouter en attribut affiché après le nom de la dalle dans l'onglet "Sélection".

C'est très important car associé au style qui va bien sur la couche cela va orienter dans le choix des dalles à extraire et donc possiblement à mettre à jour.
Concrètement : + une date est ancienne, + il est probable que la maj des données coûte chère (plus d'objets à vérifier / lever).

**Comment by fvanderbiest** [comment]
Donc il faut afficher 3 champs ? 
- id + label + date de dernière mise à jour ?
- ou juste id + date ?
- ou juste label + date ?

J'imagine que l'ordre d'affichage va être important aussi.

**Comment by MaelREBOUX** [comment]
Bilan de l'échange de ce jour :
- supprimer affichage attribut id car le vrai ID utilisé et à faire figuré dans le mail est **cases_200**
- rajouter l'affichage de l'attribut **date_der_maj**
- un nouvel attribut à afficher va être créer très rapidement : il servira à savoir si une dalle contient de la donnée topo ou pas. Je pense que ce sera 1 / 0 comme valeur ou alors un booléen True / False.

**Comment by MaelREBOUX** [comment]
@fvanderbiest la couche a été mise à jour avec les nouveaux attributs et il y a des données dedans.

**Comment by fvanderbiest** [comment]
> la couche a été mise à jour avec les nouveaux attributs

Possibilité de saisir une liste de champs et leurs types (parmi date, time, timestamp, bool, float, int, string, auto, cf http://docs.sencha.com/extjs/3.4.0/source/Types.html#Ext-data-Types-property-NUMBER) avec 04bccd8

A noter que le premier champ de la liste **doit toujours être** l'identifiant des tuiles.

**Comment by fvanderbiest** [comment]
Déployé en test, mais j'ai un souci avec le champ date.
Il est bien exporté en GFI via `<ref_topo:date_der_maj>1970-01-01</ref_topo:date_der_maj>` mais il ne s'affiche pas dans le tableau. Je vais voir ça.

**Comment by fvanderbiest** [comment]
> Je vais voir ça.

Il semblerait que les données soient en cause:
![capture du 2016-11-25 13 33 47](https://cloud.githubusercontent.com/assets/265319/20625461/d8fd3f54-b313-11e6-82a5-f3cd3f3d983e.png)

Le temps commence au 2 janvier 1970 en javascript ;-)

**Comment by fvanderbiest** [comment]
Bon, donc pour moi ce ticket est à fermer.

**Comment by MaelREBOUX** [comment]
ha zut : si tu veux que je change les valeurs : me dire.

**Comment by fvanderbiest** [comment]
> ha zut : si tu veux que je change les valeurs : me dire.

Bah faudrait y mettre des choses plus significatives dedans ;-)
