### ISSUE TITLE
Modifier la couche de carroyage à utiliser -> rctr_surf_carroyage

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/rmtr#6]
J'avais publié rapidement la couche des carreaux et revenant dessus je me suis loupé sur le nommage.

Merci de modifier l'add-on pour utiliser **toposurf:rctr_surf_carroyage **.

Une fois fait je supprimerais la mauvaise couche.

**Comment by fvanderbiest** [comment]
Fait avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/6444ed35e1f6e547bbe1d08acb0132b73ce5cc06

**Comment by MaelREBOUX** [comment]
TODO : supprimer style et couche

**Comment by fvanderbiest** [comment]
toposurf:rctr_surf_carroyage n'existe pas sur test

ref_topo:rctr_surf_carroyage existe

**Comment by MaelREBOUX** [comment]
Oui pardon : **ref_topo:rctr_surf_carroyage**

Là l'add-on ne charge pas la couche. Normal ? On voulait re-tester... Tu as redéployer / réinstaller l'add-on ?

**Comment by fvanderbiest** [comment]
Corrigé avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/e0a01dfa1d7a05e274cdd5c82a3989a2f98d227f

J'update test de suite.

**Comment by fvanderbiest** [comment]
> J'update test de suite.

fait

**Comment by MaelREBOUX** [comment]
style et couche obsolètes supprimés
