### ISSUE TITLE
Module d'envoi d'emails

### ISSUE THREAD

**Issue by fvanderbiest** [sigrennesmetropole/rmtr#9]
Je le verrais volontiers comme un nouveau module "email-proxy" ou "mailer" dans georchestra master, indépendant de cet addon.

On pourrait configurer dans https://github.com/georchestra/datadir/blob/15.12/security-proxy/security-mappings.xml qui a le droit de l'utiliser. Par défaut: tous les membres ayant le rôle "USER".

En entrée, il accepterait un JSON, par exemple:
```json
{
    "from": "me@rm.fr",
    "reply-to": "no-one@rm.fr",
    "to": ["you@rm.fr", "another-guy@rm.fr"],
    "cc": ["him@rm.fr"],
    "bcc": ["secret@rm.fr"],
    "subject": "test",
    "body": "Ceci est un test"
}
```

En config (dans le datadir) il y aurait les paramètres d'un service SMTP (comme https://github.com/georchestra/datadir/blob/15.12/extractorapp/extractorapp.properties#L10-L12).

Son rôle consisterait juste à formater et à relayer le mail au service SMTP, sans vérification de droits (puisque c'est le SP qui s'en chargerait).

**Comment by fvanderbiest** [comment]
A affecter à @Vampouille (mais il n'est pas dans ce dépot) et @pmauduit

**Comment by fvanderbiest** [comment]
Ce module pourrait de fait être utilisé par tous les addons (client-only) qui auraient besoin de notifier qqch par email.

On peut aussi se poser la question de sa généralisation aux autres modules devant envoyer des courriels (ldapadmin, extractorapp,...), mais le paradigme est un peu différent ici, car il s'agirait d'une communication server-to-server intra-geOrchestra, qui dépasse la commande actuelle.

**Comment by fvanderbiest** [comment]
Prévoir un logging mentionnant:
 * au niveau `INFO` (niveau par défaut) le vrai demandeur (`sec-username`), ses roles (`sec-roles`) et les champs suivants: `from`, `to`, `cc`, `bcc`.
 * au niveau `DEBUG` la spec JSON complète ?

(utile en cas d'abus du service)

**Comment by fvanderbiest** [comment]
Vu avec Julien:
 * pour éviter les problèmes de réputation serveur (SPF), on enlève le champ `from` de la spec, celui-ci sera un compte email paramétré en dur dans le fichier properties du module (par exemple `georchestra-noreply@rennesmetropole.fr`),
 * on fera apparaitre dans le `from` le nom réel de l'utilisateur, ex: 
```
from: François Van Der Biest <georchestra-noreply@rennesmetropole.fr>
```
 * le reply-to sera paramétré sur la valeur de `sec-email` du demandeur.
```
reply-to: françois.vanderbiest@camptocamp.com
```

**Comment by fvanderbiest** [comment]
Pour les champs `to`, `cc`, `bcc`, je suis partagé.

Soit on fait un module un peu générique (ce qui est a priori intéressant) et on laisse la possibilité au client JS (l'addon RMTR, et d'autres plus tard) de les spécifier.
Inconvénients: 
 * tout utilisateur de la plateforme (ou du moins, tout utilisateur muni du bon rôle) pourra spammer la terre entière, et éventuellement provoquer le black-listage du SMTP configuré dans ce module.
 * un petit malin qui activerait son débuggeur navigateur pourrait voir le contenu des champs to, cc, bcc. On ne répond donc pas strictement à la demande de RM de "cacher" les destinataires du mail.

Soit on fait un module 100% dédié à l'addon RMTR, et dans ce cas, seuls les champs "subject" et "body" sont envoyés par l'addon client à la partie serveur. Les champs from, to, cc, bcc, seraient alors en configuration dans les paramètres du module.
Module qui du coup devient complètement spécifique à cet addon.

**Comment by fvanderbiest** [comment]
Je veux bien des avis de @catmorales @MaelREBOUX @vampouille et @pmauduit sur ce point.
Merci !

**Comment by catmorales** [comment]
>A affecter à @Vampouille (mais il n'est pas dans ce dépot) 

Je viens de le rajouter , invitation envoyée

**Comment by catmorales** [comment]
L'option 2  spécifique à l'addon serait vraiment dommage  ! !! car cette fonctionnalité va être redemandée dans plein d'addons (entre autres le module photo obliques en cours de dev par GFI). 
Si je reprends les inconvénients de l'option 1:
* possibilité de spam et de blacklistage  : ce point est à mon avis le plus gênant cependant quand tu dis que seul les utilisateurs munis du bon rôle peuvent générer ce risque.
Il faudrait bien comprendre le mécanisme: si le mail est envoyé à l'utilisateur connecté à travers son adresse mail paramétrée dans le LDAP et pas saisie à la main, ça réduit le risque ...mais il faudrait  prévoir une option dans le cas des PF pour lesquelles l'authentification  n'est pas obligatoire.
* voir les personnes en copie : ce point est moins gênant car nous pouvons utiliser une bal générique (portail.sig.rennesmetropole.fr); c'est à mon avis une histoire d'organisation interne - à rediscuter avec F. Chauvin --> @MaelREBOUX

**Comment by fvanderbiest** [comment]
Je serais également partisan de faire qqch d'assez générique, quitte à ce que les destinataires du mail ne soient pas réellement cachés (requêtes client / serveur visibles au débuggueur).

Dans tous les cas, l'adresse email de l'expéditeur (champ `from`) **ne pourra pas** être celle de l'utilisateur dans le LDAP, car certains fournisseurs ne verraient pas d'un bon oeil qu'on envoie des mails à leur place.

**Comment by catmorales** [comment]
oui bien sur, je parlais de l'adresse destinataire , pour éviter que ce soit envoyé au monde entier ;)

**Comment by fvanderbiest** [comment]
Du coup, si je résume les échanges, on serait actuellement sur ce genre de spec en entrée:
```json
{
    "to": ["you@rm.fr", "another-guy@rm.fr"],
    "cc": ["him@rm.fr"],
    "bcc": ["secret@rm.fr"],
    "subject": "test",
    "body": "Ceci est un test"
}
```

**Comment by fvanderbiest** [comment]
Les champs `from` et `reply-to` sont gérés côté serveur en récupérant les headers `sec-username` et `sec-email`.

**Comment by catmorales** [comment]
Oui désolé je me rends compte que j'ai cafouillé dans les retours que je t'ai fait.
En prenant un exemple, ça donnerait:
c.morales est connectée et fait une demande.
* les champ from et reply to s'appuieraient sur les `sec-username et sec-email` récupérés côté serveur en l'occurrence ici c.morales et c.morales@rennesmetropole.fr,
* les autres champs seraient paramétrés par les administrateurs dans le fichier config.json de l'addon 
{
    "to": ["portail@sig.rennesmetropole.fr"],
    "cc": ["sig@rennesmetropole.fr"],
    "bcc": ["s.gelin@rennesmetropole.fr"],
    "subject": "Demande d'extraction de données topographiques",
    "body": "Ceci est un test"
}
avec le risque qu'un utilisateur qui utilise firebug puisse voir en clair les adresses mail sig.rennesmetropole.fr et s.gelin@rennesmetropole.fr.

J'attends ton retour sur ce point @MaelREBOUX (à voir avec Frédéric)

**Comment by fvanderbiest** [comment]
> les champ from et reply to s'appuieraient sur les sec-username et sec-email récupérés côté serveur

Je dirais même mieux: on peut s'appuyer sur `sec-firstname` et `sec-lastname`, d'après https://github.com/georchestra/datadir/blob/15.12/security-proxy/headers-mapping.properties#L2-L3 pour générer le champ `From`

Pour le champ `Reply-to`, on repose bien sur `sec-email` du demandeur.

**Comment by Vampouille** [comment]
> les champ from et reply to s'appuieraient sur les sec-username et sec-email

Le champ `From` ne contiendra pas l'adresse E-Mail du demandeur mais uniquement son nom.

**Comment by Vampouille** [comment]
il faut prévoir une limitation au niveau :
* nombre de destinaire (10 par exemple)
* taille du message (body) par exemple 10ko

**Comment by Vampouille** [comment]
Une manière simple d'améliorer grandement la sécurité serait de limiter l'envoi aux personnes inscrites dans l'annuaire. On va rajouter dans le datadir une "whitelist" d'adresses mails autorisées comme destinataires (en plus des adresses de l'annuaire), pour gérer d'éventuelles listes de diffusion.

**Comment by Vampouille** [comment]
Le webservice permettant l'envoi de mails sera intégré à la webapp ldapadmin car elle contient déjà la configuration vers le serveur SMTP.

**Comment by fvanderbiest** [comment]
> Le webservice permettant l'envoi de mails sera intégré à la webapp ldapadmin car elle contient déjà la configuration vers le serveur SMTP.

Oui, et le lien avec le LDAP.

**Comment by Vampouille** [comment]
> Le webservice permettant l'envoi de mails sera intégré à la webapp ldapadmin

Voici la PR : https://github.com/georchestra/georchestra/pull/1572
et la config : https://github.com/georchestra/datadir/pull/41

**Comment by fvanderbiest** [comment]
Je viens de faire la review des PRs.
Ce sera très vite mergé et on pourra mettre à jour votre config, puis réployer après.

**Comment by Vampouille** [comment]
Peut-on fermer ce ticket ?
